name: 'Chlorine'
version: '${version}'
main: 'kr.choyunjin.chlorine.Chlorine'
description: 'Just like Essentials, but almost not overrides Minecraft commands'
author: 'Cho Yunjin'
website: 'https://github.com/kmoon2437/chlorine'
api-version: '1.21.1'
libraries: # kotlin 관련해서 필요한 것들
    - org.jetbrains.kotlin:kotlin-stdlib:2.0.20
    - org.jetbrains:annotations:24.1.0

# default 값이...
# - true이면 모두에게 권한 부여
# - false이면 누구도 권한을 부여받지 않음
# - op, not op는 문자 그대로
permissions:
    chlorine.command.tell:
        description: 'Permission for /tell command'
        default: true
    chlorine.command.tpa:
        description: 'Permission for /tpa command'
        default: true

commands:
    tell:
        description: 'Whisper'
        aliases: ['w', 'msg']
        permission: 'chlorine.command.tell'
    tpa:
        description: 'Teleport request'
        permission: 'chlorine.command.tpa'